# Generated by Django 4.2.23 on 2025-08-18 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campus_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaningreservation',
            name='resident',
            field=models.OneToOneField(default=uuid.UUID('d92f7e17-c64d-4158-af56-b4509ebad3d4'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commonareareservation',
            name='resident',
            field=models.OneToOneField(default=uuid.UUID('d92f7e17-c64d-4158-af56-b4509ebad3d4'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='resident',
            field=models.OneToOneField(default=uuid.UUID('d92f7e17-c64d-4158-af56-b4509ebad3d4'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guest',
            name='resident',
            field=models.OneToOneField(default=uuid.UUID('d92f7e17-c64d-4158-af56-b4509ebad3d4'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='package',
            name='resident',
            field=models.OneToOneField(default=uuid.UUID('d92f7e17-c64d-4158-af56-b4509ebad3d4'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
