# Generated by Django 5.2.2 on 2025-06-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isFirstAccess',
            field=models.BooleanField(default=True),
        ),
    ]
