# Generated by Django 5.1.5 on 2025-06-19 12:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus_management', '0002_customuser_isfirstaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('cost', models.IntegerField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='guest',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
        migrations.AddField(
            model_name='guest',
            name='document',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='guest',
            name='documentNumber',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='guest',
            name='nights',
            field=models.IntegerField(default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('resident_manager', 'Resident Manager'), ('front_office_manager', 'Front Office Manager'), ('front_office', 'Front Office'), ('community_ambassador', 'Community Ambassador'), ('marketing', 'Marketing'), ('user', 'User'), ('resident', 'Resident')], default='guest', max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='room',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='campus_management.room'),
        ),
        migrations.CreateModel(
            name='CommmonAreaReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default=None, max_length=20)),
                ('reservationDate', models.DateField(max_length=50)),
                ('timeSlot', models.TimeField(max_length=50)),
                ('note', models.TextField()),
                ('room', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='campus_management.room')),
                ('commonArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_management.commonarea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CleaningReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default=None, max_length=20)),
                ('cleaningType', models.CharField(max_length=50)),
                ('cost', models.IntegerField(max_length=10)),
                ('requestDate', models.DateField(max_length=50)),
                ('timeSlot', models.TimeField(max_length=50)),
                ('note', models.TextField()),
                ('room', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='campus_management.room')),
                ('space', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='campus_management.commonarea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ElectricityMeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default=None, max_length=50)),
                ('readingPicture', models.FileField(upload_to='./electricMetersImages/')),
                ('electricityConsumption', models.IntegerField(max_length=10)),
                ('cost', models.IntegerField(max_length=10)),
                ('readingDate', models.DateField(max_length=50)),
                ('room', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='campus_management.room')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default=None, max_length=20)),
                ('reportDate', models.DateField(max_length=50)),
                ('faultType', models.CharField(max_length=50)),
                ('faultPhoto', models.FileField(upload_to='./faultsImages/')),
                ('note', models.TextField()),
                ('room', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='campus_management.room')),
                ('space', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='campus_management.commonarea')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus_management.campus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='room',
            name='housing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='campus_management.housing'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default=None, max_length=20)),
                ('sender', models.CharField(max_length=50)),
                ('arrivalDate', models.DateField(max_length=50)),
                ('storage', models.CharField(max_length=20)),
                ('notes', models.TextField()),
                ('room', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='campus_management.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
