# Generated by Django 5.1.5 on 2025-06-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_management', '0003_commonarea_remove_guest_check_in_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommmonAreaReservation',
            new_name='CommonAreaReservation',
        ),
    ]
