# Generated by Django 5.1.5 on 2025-06-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_management', '0004_rename_commmonareareservation_commonareareservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricitymeter',
            name='readingPicture',
        ),
    ]
