# Generated by Django 5.1.5 on 2025-06-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_management', '0005_remove_electricitymeter_readingpicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
