# Generated by Django 5.1.5 on 2025-06-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus_management', '0006_delete_worker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cleaningreservation',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='commonareareservation',
            old_name='note',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='faultreport',
            old_name='note',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='faultreport',
            name='faultPhoto',
        ),
    ]
